//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_AAsesoresAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int PropertyId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int Status { get; set; }
        public int UserId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Property Property { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
