//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_AAsesoresAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string TableName { get; set; }
        public string CurrentAudit { get; set; }
        public System.DateTime CreationDateAudit { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
