//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_AAsesoresAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDoc
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DocUrl { get; set; }
        public int PropertyId { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
