//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_AAsesoresAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Appointment = new HashSet<Appointment>();
            this.PropertyAddress = new HashSet<PropertyAddress>();
            this.PropertyDoc = new HashSet<PropertyDoc>();
            this.PropertyImg = new HashSet<PropertyImg>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int EmployeeId { get; set; }
        public int Currency { get; set; }
        public decimal Price { get; set; }
        public decimal AreaLand { get; set; }
        public decimal AreaBuild { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public int PropertyType { get; set; }
        public int Transactiontype { get; set; }
        public int PropertyStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PropertyType PropertyType1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual TransactionType TransactionType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyAddress> PropertyAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyDoc> PropertyDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyImg> PropertyImg { get; set; }
    }
}
