//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_AAsesoresAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuoteRooms()
        {
            this.QuoteDetailsPerRoom = new HashSet<QuoteDetailsPerRoom>();
        }
    
        public int Id { get; set; }
        public string RoomName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteDetailsPerRoom> QuoteDetailsPerRoom { get; set; }
    }
}
