//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_AAsesoresAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.QuoteDetailsPerRoom = new HashSet<QuoteDetailsPerRoom>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Status { get; set; }
        public string DocUrl { get; set; }
        public string Details { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteDetailsPerRoom> QuoteDetailsPerRoom { get; set; }
    }
}
